name = "wayne-ai-assistant"
account_id = "c58ef0375e8c53127a457a3b155dd006"
workers_dev = true
compatibility_date = "2025-08-05"

[vars]
ENV = "production"
# Optional: Add these if you need to reference them in your worker
OPENAI_API_KEY = "@@OPENAI_API_KEY"
GEMINI_API_KEY = "@@GEMINI_API_KEY"
STABILITY_API_KEY = "@@STABILITY_API_KEY"

[triggers]
routes = ["https://wayne-ai-assistant.mysvm.workers.dev/*"]

# Optional settings for better dev experience
[build]
command = "npm install"

[dev]
port = 8787
