name = "wayne-ai-assistant"
type = "typescript"
account_id = "c58ef0375e8c53127a457a3b155dd006"
workers_dev = true
compatibility_date = "2025-08-05"

[vars]
ENV = "production"

[triggers]
routes = ["https://wayne-ai-assistant.mysvm.workers.dev/*"]

# Optional settings for better dev experience
[build]
command = "npm install"

[dev]
port = 8787
