# wrangler.toml

name = "wayne-ai-assistant"
main = "src/worker.js"
compatibility_date = "2025-08-05"
account_id = "c58ef0375e8c53127a457a3b155dd006"
workers_dev = true

[build]
command = "npm install && npm run build"
upload.format = "service-worker"
upload.dir = "public"

[site]
bucket = "./public"
entry-point = "./src"

[observability]
enabled = true

[observability.logs]
include = ["fetch", "exception", "request", "console"]
fields = ["event", "exception", "requestId", "outcome", "duration", "cpuTime"]

[kv_namespaces]
binding = "CHAT_HISTORY"
id = "871236707f7d480fa84f129e9caa4099"
preview_id = "abcdef1234567890abcdef1234567890"  # Replace with your preview KV ID

# Additional KV namespaces if needed
# [[kv_namespaces]]
# binding = "USER_PREFERENCES"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[vars]
ENV = "production"
DEFAULT_MODEL = "gpt-3.5-turbo"

Secrets (set via wrangler secret put)
OPENAI_API_KEY = "@@OPENAI_API_KEY"
GEMINI_API_KEY = "@@GEMINI_API_KEY"
STABILITY_API_KEY = "@@STABILITY_API_KEY"

[triggers]
crons = ["0 * * * *"]  # Hourly maintenance tasks
routes = [
  "wayne-ai-assistant.*.workers.dev/*",
  "wayne-ai.example.com/*"  # Replace with your domain
]

[dev]
ip = "localhost"
port = 8787
local_protocol = "https"
